services:
  # 1. SERVICIO DE LA API FLASK
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: stitchapp-api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
      
  # 2. SERVICIO DE LA BASE DE DATOS (DB)
  db:
    image: mysql:8.0
    container_name: stitchapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Stitchapp123#$ # Aquí NO se necesita codificación
      MYSQL_DATABASE: PROY_STITCHAPP
    ports:
      - "3307:3306"
    volumes:
      - ./db_init/backup.sql:/docker-entrypoint-initdb.d/backup.sql
